apiVersion: v1
kind: Namespace
metadata:
  name: bitwarden
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: bitwarden-web
#   namespace: bitwarden
#   labels:
#     app: bitwarden
# spec:
#   ports:
#     - port: 80
#       targetPort: 80
#   selector:
#     app: bitwarden
---
apiVersion: v1
kind: Pod
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
spec:
  containers:
    - name: bitwarden
      image: bitwardenrs/server:latest
      ports:
        - containerPort: 80
---

