apiVersion: v1
kind: Namespace
metadata:
  name: bitwarden
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bitwarden
  name: bitwarden-data
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /tmp/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - orbstack
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden-web
  namespace: bitwarden
  labels:
    app: bitwarden
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: web
  selector:
    app: bitwarden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  serviceName: bitwarden
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
      - name: bitwarden
        image: bitwardenrs/server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: bitwarden-data
          mountPath: /data
        env:
          - name: ADMIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: tokens
                key: ADMIN_TOKEN
  volumeClaimTemplates:
  - metadata:
      name: bitwarden-data
      namespace: bitwarden
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      selector:
        matchLabels:
          type: local